### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by tinywrkb**
This should work.

### CODE REVIEW

**Comment by tinywrkb** [comment]
This has not been tested, so someone should try the test build and report back before merging.

**Comment by tim77** [comment]
@tinywrkb awesome, thank you! I've did very basic test and at least app starting fine. Let's try.

**Comment by tim77** [comment]
Found some weird errors on starting, but app working. Something that need to note:

```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open amdgpu: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/amdgpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: amdgpu
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: radeonsi
```

- Mesa: 21.2.3

**Comment by tinywrkb** [comment]
The app is missing `--device=dri` permission.

**Comment by tim77** [comment]
https://github.com/flathub/nz.mega.MEGAsync/commit/dd607a9d7b3eb6de914e3035a928fa22c93132ab

**Pull request merged**
